name: Build Samples

on:
  workflow_call:

jobs:
  Hello-World-APP:
    name: Hello World App
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src/hello-world-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Hello World App
        run: npm run build

      - name: Test Hello World App
        run: npm run test
