name: Build Samples

on:
  workflow_call:

jobs:
  sample-1:
    name: Sample 1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        working-directory: src/sample-1
        run: yarn install

      - name: Build Sample 1
        working-directory: src/sample-1
        run: yarn build

      - name: Test Sample 1 and create coverage report
        working-directory: src/sample-1
        run: yarn coverage

      - name: Report Sample 1 Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Sample 1 Coverage Report
          working-directory: src/sample-1
          vite-config-path: vite.config.ts
