name: Build Samples

on:
  workflow_call:

jobs:
  Hello-World-APP:
    name: Hello World App
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        working-directory: src/hello-world-app
        run: yarn install

      - name: Build Hello World App
        working-directory: src/hello-world-app
        run: yarn build

      - name: Test Hello World App and create coverage report
        working-directory: src/hello-world-app
        run: yarn coverage

      - name: Report Hello World App Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Hello World App Coverage Report
          working-directory: src/hello-world-app
          vite-config-path: vite.config.ts
